#! /bin/sh

dunst&
sxhkd &
wal -R &
notify-send -t "30000" "Welcome DinoDevil" &
compton -b &
$HOME/.config/polybar/launch.sh &

bspc monitor -d I II III IV V

bspc config border_width         0
bspc config window_gap          16

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config border_width       3
bspc config normal_border_color "#1B4552"
bspc config focused_border_color "#d5ccaa"
r
bspc config pointer_modifier mod1